### ISSUE TITLE
Stale secret deletion

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/dvc-task#119]
It looks like the following GitHub Actions secrets aren't being used in any of your workflows, at least on the default branch:
* CODECOV_TOKEN

Please ping @iterative/security before 2023-09-22 if you'd like to preserve them.

**Comment by pmrowla** [comment]
It can be removed, the token is only required for private repos so it's probably a leftover from when the dvc-task repo was first created (prior to public release)

**Comment by 0x2b3bfa0** [comment]
Thanks, @pmrowla!
