### ISSUE TITLE
no new releases since 0.0.2

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc-task#66]
In setup.cfg, there's a git dependency specified, which is currently blocking releases:
https://github.com/iterative/dvc-task/blob/dffef0795cf34cb55cc45891cdafb68e52d72b95/setup.cfg#L27

```console
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         Invalid value for requires_dist. Error: Can't have direct dependency:  
         'kombu @ git+https://github.com/celery/kombu.git@0[28](https://github.com/iterative/dvc-task/runs/6874803681?check_suite_focus=true#step:7:29)2e1419fad98da5ae956
         ff38c7e87e539889ac'
```

I know we are waiting for kombu for the release, but I am creating this issue so that we can track, and figure out if possible, a way to unblock the release. :)

**Comment by pmrowla** [comment]
This is a known issue (and why downstream dvc also installs dvc-task from git in the dev branch). There's no pressing need for a formal release of the dvc-task & dvc changes right now so I think we can keep waiting for a kombu release in the meantime.

**Comment by pmrowla** [comment]
0.1.0 is now available on pypi
