### ISSUE TITLE
worker: monitor shuts down worker prematurely

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc-task#77]
Monitor shuts down the worker after running 4-5 tasks when queue still contains additional tasks

See: https://gist.github.com/dacbd/be7648bc29f9c019410032365302e872

**Comment by dberenbaum** [comment]
@karajan1001 I'm able to reproduce this. Are you able to look into it?

**Comment by karajan1001** [comment]
> @karajan1001 I'm able to reproduce this. Are you able to look into it?



> @karajan1001 I'm able to reproduce this. Are you able to look into it?

I also experienced this several times before. But hard to tell what happened, because the log info didn't provide enough info.

**Comment by dberenbaum** [comment]
Hm, it consistently fails for me after ~5 experiments, which makes `dvc queue` unusable for more than a few experiments. Can we prioritize looking into this please?

**Comment by karajan1001** [comment]
> Hm, it consistently fails for me after ~5 experiments, which makes dvc queue unusable for more than a few experiments. Can we prioritize looking into this please?

Of course, In previous the biggest problem is that I can not reproduce it, but if we already know it definitely happens 5 experiments, investigation could be started from this point.

**Comment by dberenbaum** [comment]
I guess a good starting point would be seeing if you can also reproduce it consistently.
