### ISSUE TITLE
Permission denied when reading msg on Windows.

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc-task#93]
In the CI https://github.com/iterative/dvc/actions/runs/3310681625/jobs/5465204030

```
Permission denied: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pytest-of-runneradmin\\pytest-0\\popen-gw0\\test_queue_remove_done_2_0\\.dvc\\tmp\\exps\\run\\85b382c77c5350b90c992924313ad1745fbcef17\\85b382c77c5350b90c992924313ad1745fbcef17.json'
```

**Comment by pmrowla** [comment]
That means the file is still opened in another thread or another process. It usually means the file is not being closed properly, or we are not waiting for some other task to completely finish (and we try to open+read the file before the other task has closed it)

**Comment by pmrowla** [comment]
We probably need to lock the processinfo files in the dvc-task process manager when reading/writing to avoid potential simultaneous reads on windows

**Comment by karajan1001** [comment]
Our old naive solution in #53 greatly reduced the possibility of this kind of case, but can not prevent it. Time to solve it.
